version: "2"

linters:
  default: standard
  enable:
    - staticcheck
    - govet
    - errcheck
    - gocyclo
    - gocognit
    - goconst
    - forbidigo
    - gosec
    - unused
    #- dupl
  settings:
    gosec:
      severity: medium
    # gocyclo:
    #   min-complexity: 20
    errcheck:
      check-blank: true
      check-type-assertions: true
    # gocognit:
    #   min-complexity: 12
    dupl:
      threshold: 120
    forbidigo:
      forbid:
        - pattern: "^fmt\\.Print.*"
          msg: "Use logger instead of fmt.Print*"
  exclusions:
    rules:
      - path: "(.+)_test\\.go"
        linters:
          - errcheck
          - goconst
          - gocognit
      - path: "examples/.+\\.go"
        linters:
          - errcheck
          - forbidigo
      - path: "(.+)tool/.+\\.go"
        linters:
          - forbidigo
          - gocognit
      - path: "pkg/toolutil/.+\\.go"
        linters:
          - forbidigo
      - path: "pkg/testpayload/testpayload\\.go"
        linters:
          - gocognit
          - gocyclo
