version: "3"

vars:
  # All Go source files (excluding vendor)
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*"
  # Package list for analysis scoped to project sources
  GO_PKGS:
    sh: go list ./...

tasks:
  install-tools-mac:
    desc: Install all required Go tools on macOS
    cmds:
      - brew install golangci-lint
      - brew install aquasecurity/trivy/trivy
      - brew install govulncheck
      - brew install coreutils
      - go install github.com/google/go-licenses/v2@latest

  build:
    desc: Build all CLI tools
    cmds:
      - mkdir -p bin
      - go build -o bin/coaptool ./coaptool
      - go build -o bin/httptool ./httptool
      - go build -o bin/mqtttool ./mqtttool
      - go build -o bin/natstool ./natstool
      - go build -o bin/kafkatool ./kafkatool
      - go build -o bin/redistool ./redistool
      - go build -o bin/pubsubtool ./pubsubtool
      - go build -o bin/pgsqltool ./pgsqltool
      - go build -o bin/gittool ./gittool
      - go build -o bin/mongotool ./mongotool

  fmt-check:
    desc: Check Go code formatting without making changes
    cmds:
      - echo "Running gofmt..."
      - gofmt -d -e -l -s .

  fmt:
    desc: Format Go code with simplification
    cmds:
      - echo "Running gofmt..."
      - gofmt -s -l -w .

  lint:
    desc: Run golangci-lint across the codebase
    cmds:
      - echo "Running golangci-lint..."
      - golangci-lint run

  vet:
    desc: Run static analysis with go vet
    cmds:
      - echo "Running go vet..."
      - go vet ./...

  govulncheck:
    desc: Run Go vulnerability check with govulncheck
    cmds:
      - echo "Running govulncheck..."
      - govulncheck ./...

  test:
    desc: Run unit tests with coverage
    cmds:
      - echo "Running unit tests with coverage..."
      - go test -coverprofile=coverage.out -covermode=atomic ./pkg/...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"
      - go tool cover -func=coverage.out

  test-integration:
    desc: Run integration tests with testcontainers
    cmds:
      - echo "Running integration tests..."
      - go test ./test/integration/... -v -timeout 5m

  test-e2e:
    desc: Run end-to-end tests
    deps: [services-start]
    cmds:
      - echo "Running E2E tests..."
      - ./test/e2e/run-e2e.sh

  test-all:
    desc: Run all tests (unit, integration, e2e)
    cmds:
      - task: test
      - task: test-integration
      - task: test-e2e

  gosec:
    desc: Run security checks with gosec
    vars:
      GOSEC_INSTALLED:
        sh: command -v gosec || echo "not_found"
    cmds:
      - echo "Running gosec security scanner..."
      - gosec -exclude-generated ./...

  trivy:
    desc: Run Trivy filesystem scanner (vuln, secret, misconfig)
    vars:
    cmds:
      - echo "Running Trivy vulnerability scanner..."
      - trivy fs --scanners vuln,secret,misconfig .
      - trivy fs --format json --output trivy-results.json .

  licenses:
    desc: Check for forbidden licenses (GPL-like) and export CSV report
    cmds:
      - echo "Checking for forbidden licenses (GPL, LGPL, AGPL)..."
      - |
        go-licenses check ./... \
          --disallowed_types=GPL-2.0,GPL-3.0,LGPL-2.0,LGPL-2.1,LGPL-3.0,AGPL-1.0,AGPL-3.0 \
          || echo "⚠️  WARNING: Found forbidden licenses!"
      - echo "Generating CSV license report..."
      - go-licenses csv ./... > licenses.csv
      - echo "✅ License report saved to licenses.csv"
      - echo "Review licenses.csv to verify all dependencies"

  check:
    desc: Run all checks (fmt, lint, vet, test, gosec, trivy)
    cmds:
      - task: fmt
      - task: lint
      - task: govulncheck
      - task: trivy
      - task: licenses
      - task: test

  install-deps:
    desc: Install and tidy Go module dependencies
    cmds:
      - go mod download
      - go mod tidy

  clean:
    desc: Clean build and analysis artifacts
    cmds:
      - go clean -cache -testcache -modcache
      - rm -rf bin/
      - rm -f coverage.out
      - rm -f coverage.html
      - rm -f security-report.json
      - rm -f trivy-results.json
      - rm -f licenses.csv

  # Docker Services Management
  services-start:
    desc: Start all Docker services
    cmds:
      - echo "Starting Docker services..."
      - docker compose up -d
      - echo "Waiting for services to be ready..."
      - sleep 10
      - echo "Initializing MongoDB replica set..."
      - docker exec eventkit-mongodb mongosh --eval 'rs.initiate({_id:"rs0",members:[{_id:0,host:"localhost:27017"}]})'
      - echo "Services started successfully"

  services-stop:
    desc: Stop all Docker services
    cmds:
      - echo "Stopping Docker services..."
      - docker compose down

  services-restart:
    desc: Restart all Docker services
    cmds:
      - task: services-stop
      - task: services-start

  services-status:
    desc: Show status of all Docker services
    cmds:
      - docker compose ps

  services-logs:
    desc: Show logs from all Docker services
    cmds:
      - docker compose logs -f

  services-health:
    desc: Check health of all Docker services
    cmds:
      - echo "Checking service health..."
      - |
        echo "MQTT (NanoMQ):" && (nc -z localhost 1883 && echo "✓ Running" || echo "✗ Not accessible")
        echo "NATS:" && (nc -z localhost 4222 && echo "✓ Running" || echo "✗ Not accessible")
        echo "Redis:" && (nc -z localhost 6379 && echo "✓ Running" || echo "✗ Not accessible")
        echo "PostgreSQL:" && (nc -z localhost 5432 && echo "✓ Running" || echo "✗ Not accessible")
        echo "MongoDB:" && (nc -z localhost 27017 && echo "✓ Running" || echo "✗ Not accessible")
        echo "Kafka:" && (nc -z localhost 9092 && echo "✓ Running" || echo "✗ Not accessible")
        echo "HTTP Server:" && (nc -z localhost 8080 && echo "✓ Running" || echo "✗ Not accessible")
        echo "CoAP Server:" && (nc -zu localhost 5683 && echo "✓ Running" || echo "✗ Not accessible")

  services-clean:
    desc: Stop services and remove volumes
    cmds:
      - echo "Stopping services and cleaning volumes..."
      - docker compose down -v
      - echo "Services and volumes removed"

  # Development workflow
  dev-setup:
    desc: Setup complete development environment
    cmds:
      - task: install-deps
      - task: services-start
      - echo "Development environment ready!"

  ci:
    desc: Run CI pipeline (lint, test, build)
    cmds:
      - task: fmt-check
      - task: lint
      - task: vet
      - task: test
      - task: test-integration
      - task: build
      - echo "CI pipeline completed successfully!"
